---
title: "The Uncertainty of Reliability"
description: |
  Notions of consistency
author:
  - name: Michael Clark 
    url: https://m-clark.github.io
    affiliation: University of Michigan, CSCAR
    affiliation_url: https://cscar.research.umich.edu/
  - name: Xilin Chen
    url: https://www.procedurallearning.org/
    affiliation: University of Michigan, C-STAR
    affiliation_url: https://www.procedurallearning.org/
  - name: Seth Berry
    url: https://mendoza.nd.edu/research-and-faculty/directory/seth-berry/
    affiliation: University of Notre Dame, Mendoza
    affiliation_url: https://mendoza.nd.edu/
  - name: Josh Errickson
    url: https://errickson.net/
    affiliation: University of Michigan, CSCAR
    affiliation_url: https://cscar.research.umich.edu/
  - name: Richard Herrington
    url: https://errickson.net/
    affiliation: University of North Texas, DSA
    affiliation_url: https://it.unt.edu/research/
  - name: Brian C. George
    url: https://www.procedurallearning.org/
    affiliation: University of Michigan, PLSC
    affiliation_url: https://www.procedurallearning.org/
date: "`r Sys.Date()`"
bibliography: measurement.bib
output: 
  distill::distill_article:
    css: radix.css
    toc: true
repository_url: https://github.com/m-clark/reliability
citation_url: https://m-clark.github.io/reliability
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  eval = T,
  #comment=NA, 
  R.options=list(width=220),   
  dev.args=list(bg = 'transparent'), 
  dev='svglite',
  #fig.align='center', 
  out.width='75%', 
  fig.asp=.75,                 
  cache.rebuild=F#, 
  # cache=T
)

library(tidyverse); library(kableExtra); library(visibly); library(broom)

kable_df <- function(..., digits=3) {
  kable(..., digits=digits) %>% 
    kable_styling(full_width = F)
}

rnd = function(x, digits = 3) arm::fround(x, digits = digits)
```




<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

<div style="text-align: center; font-size: 200%">**IN PROGRESS**</div>

```{r intro, child='intro.Rmd'}
```


```{r def, child='definitions.Rmd'}
```

```{r demo, child='demo.Rmd'}
```


```{r conc, child='conclusion.Rmd'}
```









## Acknowledgments {.appendix}

Yadda yadda

## Author Contributions {.appendix}

Yadda yadda