#### Goals/Abstract

To examine reliability from different perspectives, and the uncertainty in the measurement of it.


#### Audience

Applied practitioners of statistics in fields where the reporting of reliability of measurement is commonplace (e.g. psychology, education, biomedical sciences).  Supplemental material may go deeper and be of interest to methodologists.

## The Meaning of Reliability

### What we talk about when we talk about reliability

When used in everyday discourse, no one really wonders what we mean when we say something is <span class="emph">reliable</span>.  If you are talking about a car and you say it's reliable, it means it won't break down on you.  If we talk about a person being reliable, it means we can depend on them to provide consistent behavior, e.g. regarding a specific task.  Reliable electric service means one can keep the lights on all day.  This everyday notion of reliability is closely related to the notion of dependability as well.  We can depend on the person, car, or whatever, to do what we *expect*.  Even though we may agree on this concept of reliability, pause should be taken. A reliable car from the 1970s would not meet acceptable standards for reliability these days.  Your assessment and standard of reliablity may be wholly different if talking about a brother or sister.  Thus, some fuzziness is inherent even with the everyday notion of reliability.

While we can talk about reliability from an everyday standpoint, the concept has been carried over to the realm of scientific analysis of data as well. And while the concept may be applied, it must of course become more precise, as scientific endeavor dictates.  It may surprise some that reliability has been studied scientifically for over a century.  With that knowledge however, it should not be too surprising that numerous statistical techniques have been advanced over that time, and the varieties will often align with different notions of reliability.

<aside>Charles Spearman (1904) examined the attenuation of correlation due to measurement error, but there were still earlier investigations. See Revelle chapter 7 for a brief history[@revelle_introduction_nodate].</aside>

Even when positing a specific statistic for reliability, our investigation should not end there.  As with the everyday notion of reliablity, there is <span class="emph">uncertainty</span> in the scientific measurement of it, and we should have some grasp of the nature of that uncertainty, else we risk becoming overly confident in our understanding of a measure.  Thus what holds for other statistical measures - means, regression coefficients, and so on - will apply to any measurment of reliability as well.


In what follows we seek to trace out a few of the definitions of reliability associated with some of the more common statistical measures of it.  Classical test theory will lay the foundation, after which we will explore an understanding of reliability from simple correlations, to the concept of consistency, and finally toward thinking about latent constructs and measurement error more deeply.  Demonstrations of each notion of reliability will then be provided, not focused on merely producing a statistic, but establishing the uncertainty surrounding it, and understanding it with that context.  General comparisons and contrasts about the different approaches will be made, and suggestions about practical ways to proceed offered.  And finally, much more advance and technical exploration will be undertaken in the supplemental addendum to this document.